<?php
/** @var \Mageplaza\Affiliate\Block\Affiliate\History $block */
?>
<div class="block block-dashboard-info">
    <div class="block-title"><strong><?= $block->escapeHtml(__('History')) ?></strong></div>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <thead>
                <tr>
                    <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                    <th scope="col" class="col shipping"><?= $block->escapeHtml(__('code')) ?></th>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Amount')) ?></th>
                    <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
                </tr>
            </thead>
            <tbody>

                <tr>
                    <td class="col id">aaa</td>
                    <td class="col id">aadad</td>
                    <td class="col id">21</td>
                    <td class="col id">33</td>
                </tr>

            </tbody>
        </table>
    </div>
</div>
